export const LOGIN_USER = "LOGIN_USER"
export const RELOGIN_USER = "RELOGIN_USER" 
export const POST_USER  = "POST_USER"
export const POST_ERROR  = "POST_ERROR"
export const REMOVE_POST_USER = "REMOVE_POST_USER"
export const SIGN_IN_OUT = "SIGN_IN_OUT"